import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Navbar";
import { useTheme } from '@/context/ThemeContext';
import { useEffect } from "react";
import Cursor from "@/components/Cursor";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
     const { theme, toggleTheme } = useTheme();
    useEffect(()=>{
      const storedTheme = localStorage.getItem("theme")
      if(storedTheme){
        if(storedTheme == theme){
          toggleTheme();
        }
      }
    },[])
    
  return (
    <>
      <Head>
        <title>Suryaansh Rathinam</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Cursor/>
        <Navbar/>
      </main>
    </>
  );
}
